/* exported Booking_ */
function Booking_(id) {
  if (! id) {
    throw 'Booking ID cannot be generated';
  }
  this.id = id;
  this.startTime;
  this.endTime;
  this.location; 
  this.bookedStudents;
  this.contact;
  this.project; 
  this.tape; 
  this.items;
  
  // Methods
  
  // Deals with the NULL string generated by MySQL
  // Appropriate for object because we have to follow RMSS for getting bookings
  // This would be updated if the bookings stop coming from RMSS/MySQL
  this.nullStringHandler = function(input) {
    if (input === 'NULL') {
      return null;
    } else {
      return input;
    }
  };
  
  // Getters
  
  this.getContact = function() { return this.contact; };
  this.getId = function() { return this.id; };
  this.getEndTime = function() { return this.endTime; };
  this.getItems = function() { return this.items; };
  this.getLocation = function() { return this.location; };
  this.getProject = function() { return this.project; };
  this.getStartTime = function() { return this.startTime; };
  this.getBookedStudents = function() { return this.bookedStudents; };
  this.getTape = function() { return this.tape; };
  
  // Setters
  
  /** @param {string} */
  this.setContact = function(contact) {
    contact = this.nullStringHandler(contact);
    this.contact = contact;
    return this;
  };
  
  /** Note: setId not allowed, use new Booking_(id) as setId */
  
  /** @param {string} - formatted date */
  this.setEndTime = function(endTime) {
    this.endTime = String(endTime);
    return this;
  };
  
  /** @param {string} */
  this.setItems = function(items) {
    items = this.nullStringHandler(items);
    this.items = items;
    return this;
  };
  
  /** @param {string} */
  this.setLocation = function(location) {
    this.location = location;
    return this;
  };
  
  /** @param {string} */
  this.setProject = function(project) {
    this.project = project;
    return this;
  };
  
  /** @param {string} - formatted date */
  this.setStartTime = function(startTime) {
    this.startTime = String(startTime);
    return this;
  };
  
  /** @param {string} */
  this.setBookedStudents = function(students) {
    this.bookedStudents = students;
    return this;
  };
  
  /** @param {string} */
  this.setTape = function(tape) {
    this.tape = Boolean(tape);
    return this;
  };  
  return this;
}
